-- Create a table for baby_profiles and baby_profiles_users and their policies

create table baby_profiles (
  id bigint generated by default as identity primary key
);

alter table baby_profiles
  enable row level security;

create table baby_profiles_users (
  baby_profile_id bigint references baby_profiles on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  primary key (baby_profile_id, user_id)
);

alter table baby_profiles_users
  enable row level security;

create policy "Individuals can create baby_profiles_users." on baby_profiles_users for
    insert with check (auth.uid() = user_id);

create policy "Individuals can view their own baby_profiles_users. " on baby_profiles_users for
    select using (auth.uid() = user_id);

create policy "Individuals can update their own baby_profiles_users." on baby_profiles_users for
    update using (auth.uid() = user_id);

create policy "Individuals can delete their own baby_profiles_users." on baby_profiles_users for
    delete using (auth.uid() = user_id);

create policy "Individuals can create baby_profiles." on baby_profiles for
    insert with check (true);

create policy "Individuals can view their own baby_profiles. " on baby_profiles for
    select using (id IN ( SELECT baby_profile_id FROM baby_profiles_users WHERE user_id = auth.uid() ));

create policy "Individuals can update their own baby_profiles." on baby_profiles for
    update using (id IN ( SELECT baby_profile_id FROM baby_profiles_users WHERE user_id = auth.uid() ));

create policy "Individuals can delete their own baby_profiles." on baby_profiles for
    delete using (id IN ( SELECT baby_profile_id FROM baby_profiles_users WHERE user_id = auth.uid() ));

create function public.handle_new_baby_profile()
returns trigger as $$
begin
  insert into public.baby_profiles_users (baby_profile_id, user_id)
  values (new.id, auth.uid());
  return new;
end;
$$ language plpgsql security definer;
create trigger on_baby_profile_created
  after insert on public.baby_profiles
  for each row execute procedure public.handle_new_baby_profile();
